baseURL = 'https://evthron.github.io/'
languageCode = 'zh'
defaultContentLanguage = 'zh'
defaultContentLanguageInSubdir = true
title = "Evthron's blog"
description = "Everything you need to know about the three languages."
theme = "stack"
[taxonomies]
  tag = "tags"
  category = "categories"
  language = "languages"

[languages]
  [languages.zh]
    languageCode = 'zh'
    languageName = 'ä¸­æ–‡'
    weight = 1
    [languages.zh.menus]
      [[languages.zh.menus.main]]
        identifier = "æ–‡ç« "
        name = "ğŸ“æ–‡ç« "
        pageRef = "/posts"
        weight = 10
      [[languages.zh.menus.main]]
        identifier = "ç•«"
        name = "ğŸ–¼ï¸ç•«"
        pageRef = "/gallery"
        weight = 20
      [[languages.zh.menus.main]]
        identifier = "å·¥å…·é›†"
        name = "ğŸ› ï¸å·¥å…·é›†"
        pageRef = "/toolbox"
        weight = 30
      [[languages.zh.menus.main]]
        identifier = "æ²™ç›’"
        name = "ğŸ›æ²™ç›’"
        pageRef = "/sandbox"
        weight = 25
      [[languages.zh.menus.social]]
        identifier = "github"
        name = "ğŸ±Github"
        url = "https://github.com/Evthron/"
        weight = 40

     [[languages.zh.menus.social]]
        identifier = "rss"
        name = "ğŸ“¡RSS"
        url = "/index.xml"
        weight = 50

  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    weight = 2
    [languages.en.menus]
      [[languages.en.menus.main]]
        identifier = "posts"
        name = "ğŸ“Posts"
        pageRef = "/posts"
        weight = 10
      [[languages.en.menus.main]]
        identifier = "gallery"
        name = "ğŸ–¼ï¸Gallery"
        pageRef = "/gallery"
        weight = 20
      [[languages.en.menus.main]]
        identifier = "toolbox"
        name = "ğŸ› Toobox"
        pageRef = "/toolbox"
        weight = 25
      [[languages.en.menus.main]]
        identifier = "sandbox"
        name = "ğŸ›Sandbox"
        pageRef = "/sandbox"
        weight = 30
      [[languages.en.menus.social]]
        identifier = "github"
        name = "ğŸ±Github"
        url = "https://github.com/Evthron/"
        weight = 40
     [[languages.en.menus.social]]
        identifier = "rss"
        name = "ğŸ“¡RSS"
        url = "/index.xml"
        weight = 50

  [languages.tok]
    languageCode = 'tok'
    languageName = 'toki pona'
    weight = 3
    [languages.tok.menus]
      [[languages.tok.menus.main]]
        identifier = "lipu"
        name = "ğŸ“lipu"
        pageRef = "/posts"
        weight = 10
      [[languages.tok.menus.main]]
        identifier = "sitelen"
        name = "ğŸ–¼ï¸sitelen"
        pageRef = "/gallery"
        weight = 20
      [[languages.tok.menus.main]]
        identifier = "ma weka"
        name = "ğŸ›ma pali"
        pageRef = "/sandbox"
        weight = 30
      [[languages.tok.menus.social]]
        identifier = "ma Github"
        name = "ğŸ±ma Github"
        url = "https://github.com/Evthron/"
        weight = 40
     [[languages.tok.menus.social]]
        identifier = "ilo RSS"
        name = "ğŸ“¡ilo RSS"
        url = "/index.xml"
        weight = 50

[module.hugoVersion]
extended = true
min = "0.87.0"

[params]
mainSections = [ "posts", "gallery", "toolbox" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  compact = false

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"

  [params.article]
  math = false
  toc = true
  readingTime = true

    [params.article.license]
    enabled = false
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = false
  provider = "disqus"

    [params.comments.disqusjs]

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.remark42]

    [params.comments.vssue]
    autoCreateIssue = false

    [params.comments.waline]
    emoji = [ "https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo" ]
    requiredMeta = [ "nick", "mail" ]

      [params.comments.waline.locale]
      admin = "Admin"

    [params.comments.twikoo]

    [params.comments.giscus]
    reactionsEnabled = 1
    emitMetadata = 0

    [params.comments.gitalk]

    [params.comments.cusdis]

  [params.widgets]
  homepage = [ ]
  page = [ ]

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true
