baseURL = 'https://evthron.github.io/'
languageCode = 'en'
defaultContentLanguage = 'en'
title = "Evthron's blog"
description = "Everything you need to know about the three languages."

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "ğŸ“Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "gallery"
    name = "ğŸ–¼ï¸Gallery"
    url = "/gallery"
    weight = 20

  [[menu.main]]
    identifier = "test"
    name = "ğŸ›Test"
    url = "/test"
    weight = 30

  [[menu.social]]
    identifier = "github"
    name = "ğŸ±Github"
    url = "https://github.com/Evthron/"
    weight = 40

  [[menu.social]]
    identifier = "rss"
    name = "ğŸ“¡RSS"
    url = "/index.xml"
    weight = 50

[taxonomies]
  tag = "tags"
  category = "categories"
  language = "languages"


[languages]

  [languages.en]
    languageName = "English"
    weight = 1

    [languages.zh]
    title = "ä¸­æ–‡ç¶²ç«™"
    languageName = "Chinese"
    weight = 2