baseURL = 'https://evthron.github.io/'
languageCode = 'zh'
defaultContentLanguage = 'zh'
title = "Evthron's blog"
description = "Everything you need to know about the three languages."

[taxonomies]
  tag = "tags"
  category = "categories"
  language = "languages"

[languages]
  [languages.zh]
    languageCode = 'zh'
    languageName = 'ä¸­æ–‡'
    weight = 1
    [languages.zh.menus]
      [[languages.zh.menus.main]]
        identifier = "æ–‡ç« "
        name = "ğŸ“æ–‡ç« "
        pageRef = "/posts"
        weight = 10
      [[languages.zh.menus.main]]
        identifier = "ç•«"
        name = "ğŸ–¼ï¸ç•«"
        pageRef = "/gallery"
        weight = 20
      [[languages.zh.menus.main]]
        identifier = "å·¥å…·é›†"
        name = "ğŸ› ï¸å·¥å…·é›†"
        pageRef = "/toolbox"
        weight = 25
      [[languages.zh.menus.main]]
        identifier = "æ²™ç›’"
        name = "ğŸ›æ²™ç›’"
        url = "/sandbox"
        weight = 30
      [[languages.zh.menus.social]]
        identifier = "github"
        name = "ğŸ±Github"
        url = "https://github.com/Evthron/"
        weight = 40

     [[languages.zh.menus.social]]
        identifier = "rss"
        name = "ğŸ“¡RSS"
        url = "/index.xml"
        weight = 50

  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    weight = 2
    [languages.en.menus]
      [[languages.en.menus.main]]
        identifier = "posts"
        name = "ğŸ“Posts"
        pageRef = "/posts"
        weight = 10
      [[languages.en.menus.main]]
        identifier = "gallery"
        name = "ğŸ–¼ï¸Gallery"
        pageRef = "/gallery"
        weight = 20
      [[languages.en.menus.main]]
        identifier = "toolbox"
        name = "ğŸ› Toobox"
        pageRef = "/toolbox"
        weight = 25
      [[languages.en.menus.main]]
        identifier = "sandbox"
        name = "ğŸ›Sandbox"
        url = "/sandbox"
        weight = 30
      [[languages.en.menus.social]]
        identifier = "github"
        name = "ğŸ±Github"
        url = "https://github.com/Evthron/"
        weight = 40
     [[languages.en.menus.social]]
        identifier = "rss"
        name = "ğŸ“¡RSS"
        url = "/index.xml"
        weight = 50

  [languages.tok]
    languageCode = 'tok'
    languageName = 'toki pona'
    weight = 3
    [languages.tok.menus]
      [[languages.tok.menus.main]]
        identifier = "lipu"
        name = "ğŸ“lipu"
        pageRef = "/posts"
        weight = 10
      [[languages.tok.menus.main]]
        identifier = "sitelen"
        name = "ğŸ–¼ï¸sitelen"
        pageRef = "/gallery"
        weight = 20
      [[languages.tok.menus.main]]
        identifier = "ma weka"
        name = "ğŸ›ma pali"
        url = "/sandbox"
        weight = 30
      [[languages.tok.menus.social]]
        identifier = "ma Github"
        name = "ğŸ±ma Github"
        url = "https://github.com/Evthron/"
        weight = 40
     [[languages.tok.menus.social]]
        identifier = "ilo RSS"
        name = "ğŸ“¡ilo RSS"
        url = "/index.xml"
        weight = 50