baseURL = 'https://evthron.github.io/'
languageCode = 'zh'
defaultContentLanguage = 'zh'
defaultContentLanguageInSubdir = true
title = "Evthron's blog"
# description = "Everything you need to know about the three languages."
theme = "stack"

[taxonomies]
  tag = "tags"
  category = "categories"
  language = "languages"

[languages]
  [languages.zh]
    languageCode = 'zh'
    languageName = 'ä¸­æ–‡'
    weight = 1
    [languages.zh.menus]
      [[languages.zh.menus.main]]
        identifier = "posts"
        name = "ğŸ“æ–‡ç« "
        pageRef = "/posts"
        weight = 10
      [[languages.zh.menus.main]]
        identifier = "gallery"
        name = "ğŸ–¼ï¸ç•«"
        pageRef = "/gallery"
        weight = 20
      [[languages.zh.menus.main]]
        identifier = "tweet"
        name = "ğŸ¦Tweet"
        pageRef = "/tweet"
        weight = 25
      [[languages.zh.menus.main]]
        identifier = "toolbox"
        name = "ğŸ› ï¸å·¥å…·é›†"
        pageRef = "/toolbox"
        weight = 30
      [[languages.zh.menus.main]]
        identifier = "skill"
        name = "ğŸ®æŠ€èƒ½"
        pageRef = "/skill"
        weight = 35
      [[languages.zh.menus.main]]
        identifier = "code"
        name = "âš”ï¸ ä»£ç¢¼ç­†è¨˜"
        pageRef = "/code"
        weight = 36
      [[languages.zh.menus.main]]
        identifier = "sandbox"
        name = "ğŸª£æ²™ç›’"
        pageRef = "/sandbox"
        weight = 37
      [[languages.zh.menus.social]]
        identifier = "github"
        name = "ğŸ±Github"
        url = "https://github.com/Evthron/"
        weight = 40
        [[languages.zh.menus.social.params]]
          icon = "brand-github"
      [[languages.zh.menus.social]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/Evthron"
        weight = 45
        [[languages.zh.menus.social.params]]
          icon = "brand-twitter"
      [[languages.zh.menus.social]]
        identifier = "rss"
        name = "ğŸ“¡RSS"
        url = "/zh/index.xml"
        weight = 50
        [[languages.zh.menus.social.params]]
          icon = "rss"

  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    weight = 2
    [languages.en.menus]
      [[languages.en.menus.main]]
        identifier = "posts"
        name = "ğŸ“Posts"
        pageRef = "/posts"
        weight = 10
      [[languages.en.menus.main]]
        identifier = "gallery"
        name = "ğŸ–¼ï¸Gallery"
        pageRef = "/gallery"
        weight = 20
      [[languages.en.menus.main]]
        identifier = "tweet"
        name = "ğŸ¦Tweet"
        pageRef = "/tweet"
        weight = 25
      [[languages.en.menus.main]]
        identifier = "toolbox"
        name = "ğŸ› Toobox"
        pageRef = "/toolbox"
        weight = 25
      [[languages.en.menus.main]]
        identifier = "skill"
        name = "ğŸ®Skill"
        pageRef = "/skill"
        weight = 30
      [[languages.en.menus.main]]
        identifier = "sandbox"
        name = "ğŸª£Sandbox"
        pageRef = "/sandbox"
        weight = 37
      [[languages.en.menus.social]]
        identifier = "github"
        name = "ğŸ±Github"
        url = "https://github.com/Evthron/"
        weight = 40
        [[languages.en.menus.social.params]]
          icon = "brand-github"
      [[languages.en.menus.social]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/Evthron"
        weight = 45
        [[languages.en.menus.social.params]]
          icon = "brand-twitter"
     [[languages.en.menus.social]]
        identifier = "rss"
        name = "ğŸ“¡RSS"
        url = "/en/index.xml"
        weight = 50
        [[languages.en.menus.social.params]]
          icon = "rss"

  [languages.tok]
    languageCode = 'tok'
    languageName = 'toki pona'
    weight = 3
    [languages.tok.menus]
      [[languages.tok.menus.main]]
        identifier = "posts"
        name = "ğŸ“sitelen"
        pageRef = "/posts"
        weight = 10
      [[languages.tok.menus.main]]
        identifier = "gallery"
        name = "ğŸ–¼ï¸sitelen"
        pageRef = "/gallery"
        weight = 20
      [[languages.tok.menus.main]]
        identifier = "tweet"
        name = "ğŸ¦sitelen lili"
        pageRef = "/tweet"
        weight = 25
      [[languages.tok.menus.main]]
        identifier = "sandbox"
        name = "ğŸª£ma pali"
        pageRef = "/sandbox"
        weight = 30
      [[languages.tok.menus.social]]
        identifier = "github"
        name = "ğŸ±ma Github"
        url = "https://github.com/Evthron/"
        weight = 40
        [[languages.tok.menus.social.params]]
          icon = "brand-github"
      [[languages.tok.menus.social]]
        identifier = "ma Twitter"
        name = "Twitter"
        url = "https://twitter.com/Evthron"
        weight = 45
        [[languages.tok.menus.social.params]]
          icon = "brand-twitter"
     [[languages.tok.menus.social]]
        identifier = "ilo RSS"
        name = "ğŸ“¡ilo RSS"
        url = "/tok/index.xml"
        weight = 50
        [[languages.tok.menus.social.params]]
          icon = "rss"

[module.hugoVersion]
extended = true
min = "0.129.0"

[params]
mainSections = [ "posts", "gallery", "tweet", "toolbox" ]
searchSections = [ "posts", "gallery", "tweet", "toolbox", "skill", "sandbox", "code"]
featuredImageField = "image"
rssFullContent = true
favicon = "/favicon.ico"

  [params.footer]
  since = 2023
  customText = "ğŸŒCheck out other language versions!"

  [params.dateFormat]
  published = "2006-01-02"
  lastUpdated = "2006-01-02 15:04"

  [params.sidebar]
  compact = false
  emoji = "ğŸ”¬"

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"

  [params.article]
  math = false
  toc = true
  readingTime = false

    [params.article.license]
    enabled = false
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = false
  provider = "disqus"

    [params.comments.disqusjs]

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.remark42]

    [params.comments.vssue]
    autoCreateIssue = false

    [params.comments.waline]
    emoji = [ "https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo" ]
    requiredMeta = [ "nick", "mail" ]

      [params.comments.waline.locale]
      admin = "Admin"

    [params.comments.twikoo]

    [params.comments.giscus]
    reactionsEnabled = 1
    emitMetadata = 0

    [params.comments.gitalk]

    [params.comments.cusdis]

  # [params.widgets]

  # [[params.widgets.homepage]]
  #     type = "categories"
  #   [params.widgets.homepage.params]
  #     limit = 10
  # [[params.widgets.homepage]]
  #     type = "tag-cloud"
  #     [params.widgets.homepage.params]
  #     limit = 20

  # [[params.widgets.page]]
  #     type = "toc"
  # [[params.widgets.page]]
  #     type = "categories"
  #     [params.widgets.page.params]
  #     limit = 10
      

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[markup.goldmark.parser.attribute]
block = true # default is false
